In [1]:
import numpy as np
print(np.array([1,2,3]) * 2)

[2 4 6]


In [1]:
import numpy as np
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
import numpy as np
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
import numpy as np 
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
import numpy as np
a=np.array([[1,1,1],[1,1,1],[1,1,1]])
a.shape

(3, 3)

In [14]:
import numpy as np
print((np.eye(3)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
import numpy as np
print((np.linspace(0,1,2)))

[0. 1.]


In [19]:
import numpy as np
a=np.arange(12)
print(a.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [24]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A[1])
print(A[:,2])

[4 5 6]
[3 6 9]


In [25]:
import numpy as np 
a=np.array([[1,2,3,4,5]])
b=np.array([[10,20,30,40,50]])
print(a+b)
print(a*b)
print(a**2)
print(b**2)
print(b/a)

[[11 22 33 44 55]]
[[ 10  40  90 160 250]]
[[ 1  4  9 16 25]]
[[ 100  400  900 1600 2500]]
[[10. 10. 10. 10. 10.]]


In [26]:
A = np.array([[1,2,3],[4,5,6]])
b = np.array([10, 20, 30])
print(A + b)


[[11 22 33]
 [14 25 36]]


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.dot(a,b))
print(a@b)


32
32


In [34]:
import numpy as np
A=np.array([[1,2],[3,4],[5,6]])
B=np.array([[7,8,9],[10,11,12]])
print(A@B)
print(np.matmul(A,B))
print(A.T)

[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]
[[1 3 5]
 [2 4 6]]


In [36]:
import numpy as np
arr = np.array([4, 7, 2, 9, 1, 5, 8, 3, 6])
print(arr.mean())
print(arr.sum())
print(np.median(arr))
print(arr.max())
print(arr.min())


5.0
45
5.0
9
1


In [37]:
import numpy as np

a = np.array([1, 2, 3])
B = np.array([[1, 2], [3, 4], [5, 6]])

print(a.shape)
print(B.shape)
print(B.T)
print(B.reshape(2, 3))
print(B[1:, :])

(3,)
(3, 2)
[[1 3 5]
 [2 4 6]]
[[1 2 3]
 [4 5 6]]
[[3 4]
 [5 6]]


In [38]:
def matmult(A,B) :
    rows_A = len(A)
    cols_A = len(A[0])
    cols_B = len(B[0])
    result = [[0] * cols_B for _ in range(rows_A)]
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j]+= A[i][k]*B[k][j]
    return result
A = [[1,2],[3,4]]
B = [[5,6],[7,8]]
print(matmult(A, B))
print(np.array([[1,2],[3,4]]) @ np.array([[5,6],[7,8]]))

[[19, 22], [43, 50]]
[[19 22]
 [43 50]]
